/* Generated By:JavaCC: Do not edit this line. BafParserTreeConstants.java Version 6.0_1 */
package org.infinity.resource.bcs.parser;

public interface BafParserTreeConstants
{
  public int JJTSC = 0;
  public int JJTSEQ_TR = 1;
  public int JJTSEQ_AC = 2;
  public int JJTCR = 3;
  public int JJTCO = 4;
  public int JJTRS = 5;
  public int JJTRE = 6;
  public int JJTVOID = 7;
  public int JJTTR = 8;
  public int JJTPARAM = 9;
  public int JJTAC = 10;
  public int JJTPARAM_STR = 11;
  public int JJTPARAM_NUM = 12;
  public int JJTOR_EXPR = 13;
  public int JJTPARAM_SYM = 14;
  public int JJTPARAM_TGT = 15;
  public int JJTNAME = 16;
  public int JJTNUMERIC = 17;
  public int JJTSTRING = 18;
  public int JJTTARGET = 19;
  public int JJTOBJECT = 20;
  public int JJTSYMBOL = 21;
  public int JJTRECT = 22;
  public int JJTUINT = 23;
  public int JJTSINT = 24;
  public int JJTSIGN = 25;
  public int JJTNEG = 26;


  public String[] jjtNodeName = {
    "SC",
    "SEQ_TR",
    "SEQ_AC",
    "CR",
    "CO",
    "RS",
    "RE",
    "void",
    "TR",
    "PARAM",
    "AC",
    "PARAM_STR",
    "PARAM_NUM",
    "OR_EXPR",
    "PARAM_SYM",
    "PARAM_TGT",
    "NAME",
    "NUMERIC",
    "STRING",
    "TARGET",
    "OBJECT",
    "SYMBOL",
    "RECT",
    "UINT",
    "SINT",
    "SIGN",
    "NEG",
  };
}
/* JavaCC - OriginalChecksum=e027f5ab1d18f003c260920d3624296e (do not edit this line) */
